const sourceSongs = [
    { file: "Adele - Someone Like You.mp3", title: "Adele - Someone Like You"},
    { file: "Aitana - SUPERESTRELLA.mp3", title: "Aitana - SUPERESTRELLA", patrocinador: "Alba", imagen: "img/alba.jpg" },
    { file: "Benson Boone - Beautiful Things.mp3", title: "Benson Boone - Beautiful Things"},
    { file: "Rafael - Mi gran noche.mp3", title: "Rafael - Mi gran noche", patrocinador: "Gerard", imagen: "img/gerard.jpg"},
    { file: "ROSALÍA - La Perla.mp3", title: "ROSALÍA - La Perla"},
    { file: "Las Ketchup - Aserejé.mp3", title: "Las Ketchup - Aserejé", patrocinador: "Fernando", imagen: "img/fernando.jpg"},
    { file: "Tom Jones - It's Not Unusual.mp3", title: "Tom Jones - It's Not Unusual"},
    { file: "Camela - Cuando zarpa el amor.mp3", title: "Camela - Cuando zarpa el amor", patrocinador: "Gemma", imagen: "img/gemma.jpg"},
    { file: "Los Cantantes - El venao.mp3", title: "Los Cantantes - El venao"},
    { file: "Juan Luis Guerra - La Bilirrubina.mp3", title: "Juan Luis Guerra - La Bilirrubina"},
    { file: "Figa Flawas - LA MARINA STA MORENA.mp3", title: "Figa Flawas - LA MARINA STA MORENA", patrocinador: "Yanira", imagen: "img/yanira.jpg"},
    { file: "Hombres G - Devuélveme a mi chica.mp3", title: "Hombres G - Devuélveme a mi chica"},
    { file: "Diego Torres - Color Esperanza.mp3", title: "Diego Torres - Color Esperanza"},
    { file: "David Bisbal - Ave Maríau.mp3", title: "David Bisbal - Ave María"},
    { file: "Miguel Bosé - Amante Bandido.mp3", title: "Miguel Bosé - Amante Bandido", patrocinador: "Yaya Pili", imagen: "img/yayapili.jpg"},
    { file: "Michael Jackson - Beat It.mp3", title: "Michael Jackson - Beat It"},
    { file: "Madonna - Like A Prayer.mp3", title: "Madonna - Like A Prayer"},
    { file: "Ricchi e poveri - Sera porque te amo.mp3", title: "Ricchi e poveri - Sera porque te amo"},
    { file: "ABBA - Dancing Queen.mp3", title: "ABBA - Dancing Queen"},
    { file: "Estopa - La Raja de Tu Falda.mp3", title: "Estopa - La Raja de Tu Falda", patrocinador: "Imanol", imagen: "img/imanol.jpg" },
    { file: "ALASKA + DINARAMA - NI TÚ NI NADIE.mp3", title: "ALASKA + DINARAMA - NI TÚ NI NADIE"},
    { file: "Chenoa - Cuando tú vas.mp3", title: "Chenoa - Cuando tú vas"},
    { file: "Miguel Rios - Bienvenidos.mp3", title: "Miguel Rios - Bienvenidos"},
    { file: "Joaquin Sabina - 19 Dias Y 500 Noches.mp3", title: "Joaquin Sabina - 19 Dias Y 500 Noches"},
    { file: "Romeo Santos - Propuesta Indecente.mp3", title: "Romeo Santos - Propuesta Indecente", patrocinador: "Marc", imagen: "img/marc.jpg"},
    { file: "Chayanne - Torero.mp3", title: "Chayanne - Torero"},
    { file: "Alejandro Sanz - Corazón partío.mp3", title: "Alejandro Sanz - Corazón partío"},
    { file: "Marc Anthony - Vivir Mi Vida.mp3", title: "Marc Anthony - Vivir Mi Vida"},
    { file: "ROSALÍA - DESPECHÁ.mp3", title: "ROSALÍA - DESPECHÁ"},
    { file: "Manuel Turizo - La Bachata.mp3", title: "Manuel Turizo - La Bachata"},
    { file: "Manolo Escobar - Que Viva España.mp3", title: "Manolo Escobar - Que Viva España", patrocinador: "Gines", imagen: "img/gines.jpg"},
    { file: "Abraham Mateo, Ana Mena - Quiero Decirte.mp3", title: "Abraham Mateo, Ana Mena - Quiero Decirte"},
    { file: "Roy Orbison - Oh, Pretty Woman.mp3", title: "Roy Orbison - Oh, Pretty Woman", patrocinador: "Jenny", imagen: "img/jenny.jpg"},
    { file: "KAROL G - Si Antes Te Hubiera Conocido.mp3", title: "KAROL G - Si Antes Te Hubiera Conocido"},
    { file: "Umberto Tozzi - Gloria.mp3", title: "Umberto Tozzi - Gloria"},
    { file: "Luis Miguel - Suave.mp3", title: "Luis Miguel - Suave"},
    { file: "Fran Perea - Uno mas uno son 7.mp3", title: "Fran Perea - Uno mas uno son 7", patrocinador: "Yasmine", imagen: "img/yasmine.jpg"},
    { file: "Carlos Baute - Colgando en tus manos.mp3", title: "Carlos Baute - Colgando en tus manos"},
    { file: "Mecano - Me colé en una fiesta.mp3", title: "Mecano - Me colé en una fiesta"},
    { file: "Spice Girls - Wannabe.mp3", title: "Spice Girls - Wannabe"},
    { file: "Backstreet Boys - Everybody.mp3", title: "Backstreet Boys - Everybody"},
    { file: "Andy & Lucas - Son De Amores.mp3", title: "Andy & Lucas - Son De Amores", patrocinador: "Rosi", imagen: "img/rosi.jpg"},
    { file: "Andy & Lucas - Y En Tu Ventana.mp3", title: "Andy & Lucas - Y En Tu Ventana"},
    { file: "Miguel Bose - Como un lobo.mp3", title: "Miguel Bose - Como un lobo"},
    { file: "Mayonesa - Chocolate.mp3", title: "Mayonesa - Chocolate"},
    { file: "Gloria Gaynor - I Will Survive.mp3", title: "Gloria Gaynor - I Will Survive"},
    { file: "Vicco - Nochentera.mp3", title: "Vicco - Nochentera", patrocinador: "Pili", imagen: "img/pili.jpg"},
    { file: "Rocío Dúrcal - La Gata Bajo La Lluvia.mp3", title: "Rocío Dúrcal - La Gata Bajo La Lluvia"},
    { file: "El Fary - El Toro Guapo.mp3", title: "El Fary - El Toro Guapo", patrocinador: "Manolo", imagen: "img/manolo.jpg"},
    { file: "Zapato veloz - Tractor amarillo.mp3", title: "Zapato veloz - Tractor amarillo"},
    { file: "Sergio Dalma - Yo no te pido la luna.mp3", title: "Sergio Dalma - Yo no te pido la luna"},
    { file: "El Fary - Carabirubi.mp3", title: "El Fary - Carabirubi"},
    { file: "Lolita - Sarandonga.mp3", title: "Lolita - Sarandonga"},
    { file: "Los Secretos - Dejame.mp3", title: "Los Secretos - Dejame"},
    { file: "Danza invisible - Sabor de amor.mp3", title: "Danza invisible - Sabor de amor"},
    { file: "Juanes - La Camisa Negra.mp3", title: "Juanes - La Camisa Negra"},
    { file: "Sonia y Selena - Yo Quiero Bailar.mp3", title: "Sonia y Selena - Yo Quiero Bailar", patrocinador: "Estefania", imagen: "img/estefania.jpg"},
    { file: "Rigoberta Bandini - AY MAMÁ.mp3", title: "Rigoberta Bandini - AY MAMÁ"},
    { file: "Antonio Orozco, Malu - Devuelveme La Vida.mp3", title: "Antonio Orozco, Malu - Devuelveme La Vida"},
    { file: "Raffaella Carrà - Hay Que Venir Al Sur.mp3", title: "Raffaella Carrà - Hay Que Venir Al Sur"},
    { file: "Chayanne - Madre Tierra.mp3", title: "Chayanne - Madre Tierra"},
    { file: "El Canto del Loco - Zapatillas.mp3", title: "El Canto del Loco - Zapatillas"},
    { file: "La Pegatina - Mari Carmen.mp3", title: "La Pegatina - Mari Carmen"},
    { file: "Bongo Botrako - Todos los días sale el sol.mp3", title: "Bongo Botrako - Todos los días sale el sol"},
    { file: "Beyoncé - Crazy In Love ft. JAY Z.mp3", title: "Beyoncé - Crazy In Love ft. JAY Z"},
    { file: "Elvis Presley - Jailhouse Rock.mp3", title: "Elvis Presley - Jailhouse Rock"},
    { file: "Shakira - La Tortura.mp3", title: "Shakira - La Tortura"},
    { file: "Queen - Don't Stop Me Now.mp3", title: "Queen - Don't Stop Me Now", patrocinador: "Cristian", imagen: "img/cristian.jpg"},
    { file: "Survivor - Eye Of The Tiger.mp3", title: "Survivor - Eye Of The Tiger"},
    { file: "Whitney Houston - I Wanna Dance With Somebody.mp3", title: "Whitney Houston - I Wanna Dance With Somebody"},
    { file: "Rosa - Europe's Living A Celebration.mp3", title: "Rosa - Europe's Living A Celebration"},
    { file: "Azúcar Moreno - Sólo Se Vive una Vez.mp3", title: "Azúcar Moreno - Sólo Se Vive una Vez"},
    { file: "El Barrio - Pa Madrid.mp3", title: "El Barrio - Pa Madrid"},
    { file: "Junco - Hola Mi Amor.mp3", title: "Junco - Hola Mi Amor", patrocinador: "Paqui", imagen: "img/paqui.jpg"},
    { file: "Monica Naranjo - Desatame.mp3", title: "Monica Naranjo - Desatame"},
    { file: "Thalia - Arrasando.mp3", title: "Thalia - Arrasando"},
    { file: "Conchita Velasco - Chica ye ye.mp3", title: "Conchita Velasco - Chica ye ye"},
    { file: "El arrebato - Búscate un hombre que te quiera.mp3", title: "El arrebato - Búscate un hombre que te quiera"},
    { file: "María Isabel - Antes Muerta Que Sencilla.mp3", title: "María Isabel - Antes Muerta Que Sencilla"},
    { file: "El simbolo - Levantando las Manos.mp3", title: "El simbolo - Levantando las Manos"},
    { file: "Los Manolos - Amigos para Siempre.mp3", title: "Los Manolos - Amigos para Siempre"},
    { file: "Navajita Platea - Noches de Bohemia.mp3", title: "Navajita Platea - Noches de Bohemia"},
    { file: "Celia Cruz - La Vida Es Un Carnaval.mp3", title: "Celia Cruz - La Vida Es Un Carnaval", patrocinador: "Jordi", imagen: "img/jordi.jpg"},
    { file: "Gipsy Kings - Volare.mp3", title: "Gipsy Kings - Volare"},
    { file: "Luis Fonsi - Despacito ft. Daddy Yankee.mp3", title: "Luis Fonsi - Despacito ft. Daddy Yankee"},
    { file: "Camilo Sesto - Vivir Así Es Morir de Amor.mp3", title: "Camilo Sesto - Vivir Así Es Morir de Amor"},
    { file: "King Africa - Paquito El Chocolatero.mp3", title: "King Africa - Paquito El Chocolatero"},
    { file: "SHAKIRA __ BZRP Music Sessions #53.mp3", title: "SHAKIRA __ BZRP Music Sessions #53"},
    { file: "DUKI - GIVENCHY.mp3", title: "DUKI - GIVENCHY"},
    { file: "Estopa - Como Camaron.mp3", title: "Estopa - Como Camaron", patrocinador: "Luis", imagen: "img/luis.jpg"}
  
];

